# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [heyday, Ricky]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username next
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audible
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username king
issuehunt: # Replace with a single IssueHunt username atom
otechie: # Replace with a single Otechie username hart
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://cspire.com', 'https://cdc.gov, 'https://www.sans.org/security-awareness-training/resources/social-media-privacy.http://bit.ly/1MXCgFA']
